apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/sunsh0602/k8s_lab.git
      targetRevision: master
      ref: local-git

    - repoURL: https://openebs.github.io/openebs
      chart: openebs
      targetRevision: 4.1.1   # ⚠️ 최신 버전 확인 후 고정 (helm search repo openebs/openebs --versions)
      helm:
        releaseName: openebs
        valueFiles:
          - $local-git/03-openebs/values/dev/openebs.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openebs

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
