apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/sunsh0602/k8s_lab.git
      targetRevision: master
      ref: local-git

    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.18   # ⚠️ 최신 안정 버전 확인 후 고정 (helm search repo jenkinsci/jenkins --versions)
      helm:
        releaseName: jenkins
        valueFiles:
          - $local-git/08-jenkins/values/dev/jenkins.yaml

    - repoURL: https://github.com/sunsh0602/k8s_lab.git
      targetRevision: master
      path: 08-jenkins/manifests/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
