apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-prod # [필수] 최상위 운영계 마스터 앱의 고유 식별 명칭
  namespace: argocd  # [필수] ArgoCD 엔진이 동작 중인 시스템 네임스페이스
spec:
  project: default   # [필수] 이 마스터 앱을 귀속시킬 ArgoCD 프로젝트 그룹
  source:
    repoURL: 'https://github.com/sunsh0602/k8s_lab.git' # [필수] 하위 지시서(YAML)들이 저장된 내 원격 Git 주소
    targetRevision: master # [필수] 추적할 대상 Git 브랜치명
    path: argocd-apps/prod  # [필수] ArgoCD가 감시하여 하위 앱들을 읽어갈 Git 내부의 특정 폴더 경로
  destination:
    server: 'https://kubernetes.default.svc' # [필수] 자원들이 생성될 목적지 쿠버네티스 API 엔드포인트
    namespace: argocd  # [⚠️초핵심] 하위 '지시서(Application CRD)'들도 무조건 argocd 네임스페이스에 생성되어야 자동 인식됨
  syncPolicy:
    automated:
      prune: true      # [선택] Git 폴더에서 특정 지시서 파일이 삭제되면 클러스터에서도 해당 앱을 자동 제거할지 여부
      selfHeal: true   # [선택] 클러스터 상태가 Git에 정의된 지시서 구조와 틀어지면 자동 복구할지 여부
